export const PALETTES = {
  strawberry: {
    name: "草莓奶昔",
    bg: "#ffeef2",
    bgSoft: "#ffd9e3",
    card: "#fff5f7",
    cardWarm: "#fff0ec",
    primary: "#ff6f91",
    primaryDeep: "#e0356a",
    accent: "#ffb74d",
    ink: "#3a1f2b",
    inkSoft: "#7a5a68",
    dotA: "#ff6f91",
    dotB: "#ffc857",
    dotMuted: "#f0d4dc",
  },
  blueberry: {
    name: "蓝莓星空",
    bg: "#e9edff",
    bgSoft: "#d3daff",
    card: "#eef1ff",
    cardWarm: "#f3eeff",
    primary: "#7a8bff",
    primaryDeep: "#3d4ed3",
    accent: "#ff9bd2",
    ink: "#1f2348",
    inkSoft: "#5b6090",
    dotA: "#7a8bff",
    dotB: "#ff9bd2",
    dotMuted: "#d8dcf3",
  },
  matcha: {
    name: "抹茶布丁",
    bg: "#e6f4e1",
    bgSoft: "#cfe6c8",
    card: "#eff7eb",
    cardWarm: "#fbf5e8",
    primary: "#7bbf6a",
    primaryDeep: "#3f8c2f",
    accent: "#ffae5c",
    ink: "#1f3320",
    inkSoft: "#5a7657",
    dotA: "#7bbf6a",
    dotB: "#ffae5c",
    dotMuted: "#d2e6cd",
  },
};
